CREATE DATABASE IF NOT EXISTS lutong_bahay CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lutong_bahay;
SET time_zone = '+08:00';
CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE recipes (
 id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, category_id INT NOT NULL,
 title VARCHAR(150) NOT NULL, description TEXT NOT NULL, instructions TEXT NOT NULL,
 is_edited BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_created (created_at, id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
CREATE TABLE ingredients (
 id INT AUTO_INCREMENT PRIMARY KEY, recipe_id INT NOT NULL,
 ingredient_name VARCHAR(255) NOT NULL, sort_order INT NOT NULL,
 UNIQUE KEY recipe_order (recipe_id, sort_order),
 FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE comments (
 id INT AUTO_INCREMENT PRIMARY KEY, recipe_id INT NOT NULL, user_id INT NOT NULL,
 content TEXT NOT NULL, is_edited BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE favorites (
 user_id INT NOT NULL, recipe_id INT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (user_id, recipe_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
) ENGINE=InnoDB;
INSERT INTO categories (name) VALUES
 ('Breakfast'), ('Main Dishes'), ('Soups & Stews'), ('Vegetables'),
 ('Seafood'), ('Snacks & Merienda'), ('Desserts'), ('Rice & Noodles');
